name: mingpt
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cudatoolkit=10.1.243
  - freetype=2.10.2
  - intel-openmp=2020.1
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - ninja=1.10.0
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - pillow=7.2.0
  - pip=20.2.2
  - python=3.8.5
  - pytorch=1.6.0
  - readline=8.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - torchvision=0.7.0
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - antlr4-python3-runtime==4.8
    - argon2-cffi==20.1.0
    - attrs==19.3.0
    - backcall==0.2.0
    - bleach==3.1.5
    - cffi==1.14.2
    - chardet==3.0.4
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - hydra-core==1.0.0rc3
    - idna==2.10
    - importlib-resources==3.0.0
    - ipykernel==5.3.4
    - ipython==7.17.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.6
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - notebook==6.1.3
    - omegaconf==2.0.1rc11
    - packaging==20.4
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.6
    - ptyprocess==0.6.0
    - pycparser==2.20
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - qtconsole==4.7.6
    - qtpy==1.9.0
    - requests==2.24.0
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.4
    - tqdm==4.48.2
    - traitlets==4.3.3
    - typing-extensions==3.7.4.2
    - urllib3==1.25.10
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
